apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-command
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          echo "Custom command started"
          sleep 10
          echo "Custom command completed"
