#!/bin/bash

read -p "Enter your name for the record: " user_input_name

mkdir -p output_files
touch output_files/running_processes.txt

current_date=$(date)
host_name=$(hostname)
current_user=$(whoami)
disk_usage=$(df -h /)

echo "--- System Information Report ---"
echo "Generated by: $user_input_name"
echo "Date: $current_date"
echo "Hostname: $host_name"
echo "User: $current_user"
echo "--- Disk Usage ---"
echo "$disk_usage"
echo "---------------------------------"

ps aux > output_files/running_processes.txt

echo "Done! Running processes have been saved to output_files/running_processes.txt"